---
title: "Project Membach"
author: "Marco Ciotola"
output:
  pdf_document:
    keep_tex: yes
    fig_width: 6.5
    fig_height: 4
#  html_document:
#    mathjax: local
#    self_contained: no
#    fig_width: 6.5
#    fig_height: 4
---

```{r set mems, include=FALSE}
# MEMS
domain <- c(-7200,7200); pattern <- "MEM.*\\.csv"; name <- "MEM"; description <- "Membach"; proj_file <- 'proj.mems.RData'
```

```{r project, child='project.Rmd'}
```


```{r bc acf-pacf}
train.bc %>% ggtsdisplay(lag.max = 168*4)
train.bc %>% diff() %>% ggtsdisplay(lag.max = 168*4)
train.bc %>% diff(lag=24) %>% ggtsdisplay(lag.max = 168)
train.bc %>% diff() %>% diff(lag=24) %>% ggtsdisplay(lag.max = 168)
train.bc %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168*4)
train.bc %>% diff() %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168*4) # arima (0,1,0)(0,1,1)[168]
# acf cuts off after p=168, pacf shows peaks each 168
train.bc %>% diff() %>% diff(lag=24) %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168*4)
```

```{r diffs/bc-d168-acf-pacf}
plot_grid(
  train.bc %>% diff(lag=168) %>%  acf(lag.max = 24,    plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  train.bc %>% diff(lag=168) %>%  acf(lag.max = 168*4, plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  train.bc %>% diff(lag=168) %>% pacf(lag.max = 24,    plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  train.bc %>% diff(lag=168) %>% pacf(lag.max = 168*4, plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  nrow = 2
)
```

```{r diffs/bc-d-d168-acf-pacf}
plot_grid(
  train.bc %>% diff() %>% diff(lag=168) %>%  acf(lag.max = 24,    plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  train.bc %>% diff() %>% diff(lag=168) %>%  acf(lag.max = 168*4, plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  train.bc %>% diff() %>% diff(lag=168) %>% pacf(lag.max = 24,    plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  train.bc %>% diff() %>% diff(lag=168) %>% pacf(lag.max = 168*4, plot = F, na.action = na.pass) %>% autoplot() + labs(title = NULL) + scale_x_continuous()
  ,
  nrow = 2
)
```

## Arima
```{r arima}
to_test <- list(
  c(0,1,0,0,1,1),
  c(2,0,0,0,1,1),
  #c(3,0,0,0,1,1),
  c(0,1,1,0,1,1) #,
  #c(0,1,2,0,1,1)
)

if (!exists("models")){
  models <- list()
}

for (model in to_test) {
  # model <- c(4,1,2,0,1,0)
  fit.name <- paste0("fit", paste0(model, collapse = ""))
  forecast.name <- paste0("forecast", paste0(model, collapse = ""))
  cat("SARIMA(", paste0(model[1:3], collapse = ","), ")(", paste0(model[4:6], collapse = ","), ")[", frequency(seis.h.train), "]", sep = "")
  if (!(fit.name %in% names(models))) {
    cat(" fitting...")
    models[[fit.name]] <- Arima(seis.h.train, model[1:3], model[4:6], lambda=train.bc.lambda)
    cat("DONE")
  }
  if (!(forecast.name %in% names(models))) {
    cat(" forecasting...")
    models[[forecast.name]] <- forecast(models[[fit.name]], h=168*18, lambda=train.bc.lambda)
    cat("DONE")
  }
  cat("\n")
  plotting.model <- models[[fit.name]]
  plotting.forecast <- models[[forecast.name]]
  cat("AIC =",plotting.model$aic, "\n")
  cat("AICc =",plotting.model$aicc, "\n")
  checkresiduals(plotting.model)
  residuals.acf <- autoplot(acf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=168*4)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method))
  residuals.pacf <- autoplot(pacf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=168*4)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method))
  print(plot_grid(residuals.acf, residuals.pacf, nrow=2))
  print(plot_grid(
    autoplot(acf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=24)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method))
    ,
    residuals.acf
    ,
    autoplot(pacf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=24)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method))
    ,
    residuals.pacf
    ,
    nrow = 2
  ))
  print(plot_forecast(plotting.forecast) + autolayer(seis.h.test, series="Original") + ylab("Mean hourly movement (nm)"))
  plots <- show_overlap_and_diff(
    seis.h.train, plotting.forecast$fitted, xlab=seasonality.xlab,
    base.desc = "training set",
    compare.desc = paste0("refit with ", plotting.forecast$method),
    overlap.ylab = "Mean hourly movement (nm)",
    diff.title = "Difference between ts",
    diff.ylab = "nm", diff.ylab.sec="%",
    diff.ylab.sec.accuracy = .01
  )
  print(plot_grid(plots[[1]], plots[[2]], nrow = 2))
  
  cat("Test set inside the CI\n")
  cat("80% CI \t ", print_dec(mean(plotting.forecast$lower[,1] < seis.h.test & seis.h.test < plotting.forecast$upper[,1], na.rm = T)*100), "%\n")
  cat("95% CI \t ", print_dec(mean(plotting.forecast$lower[,2] < seis.h.test & seis.h.test < plotting.forecast$upper[,2], na.rm = T)*100), "%\n")

  plots <- show_overlap_and_diff(
    seis.h.test, plotting.forecast$mean, xlab=seasonality.xlab,
    base.desc = "test set",
    compare.desc = paste0("forecast with ", plotting.forecast$method),
    overlap.ylab = "Mean hourly movement (nm)",
    diff.title = "Difference between ts",
    diff.ylab = "nm", diff.ylab.sec="%",
    diff.ylab.sec.accuracy = .01
  )
  print(plot_grid(plots[[1]], plots[[2]], nrow = 2))
    
  print(accuracy(plotting.forecast, seis.h.test))
  # qqPlot(plotting.model$residuals, main = paste0("Q-Q plot for ", plotting.forecast$method), xlab = "residuals")
  print(gg_qqplot(plotting.model$residuals) + 
      labs(title=paste0("Q-Q plot for ", plotting.forecast$method, " residuals")) + ylab("Residuals quantiles")
  )
}


```

```{r auto arima, eval=FALSE, include=FALSE}
fit <- auto.arima(seis.h.train, lambda=train.bc.lambda, d=1, D=1, max.p=5, max.q=2, max.P=5, max.Q=2, max.order=10, trace = T)
models[["forecast011011"]]$mean
```

## Arima without seasonality
```{r arima on seasonality}
autoplot(residuals+trend.s)
residuals.bc.lambda <- BoxCox.lambda(residuals+trend.s)
residuals.bc <- BoxCox(residuals+trend.s, residuals.bc.lambda)
residuals.bc %>% ggtsdisplay(lag.max = 168*5)
residuals.bc %>% diff() %>% ggtsdisplay(lag.max = 168*5)
residuals.bc %>% diff(lag=24) %>% ggtsdisplay(lag.max = 168)
residuals.bc %>% diff() %>% diff(lag=24) %>% ggtsdisplay(lag.max = 168)
residuals.bc %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168*5)
residuals.bc %>% diff() %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168*5) # arima (0,1,0)(0,1,1)[168]
residuals.bc %>% diff() %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168) # arima (0,1,0)(0,1,1)[168]
# acf cuts off after p=168, pacf shows peaks each 168
residuals.bc %>% diff() %>% diff(lag=24) %>% diff(lag=168) %>% ggtsdisplay(lag.max = 168*5)

gg_qqplot(residuals) + 
  labs(title=paste0("Q-Q plot for ", plotting.forecast$method, " residuals")) + ylab("Residuals quantiles")


a <- Arima(residuals, order = c(1,0,0), seasonal = c(0,0,0), lambda=residuals.bc.lambda)
afor <- forecast(a, h=168*18, lambda=residuals.bc.lambda)

plotting.model <- a
plotting.forecast <- afor

autoplot(plotting.model) + xlab("Week")

gg_qqplot(plotting.model$residuals) + 
  labs(title=paste0("Q-Q plot for ", plotting.forecast$method, " residuals")) + ylab("Residuals quantiles")
checkresiduals(plotting.model$residuals)
Box.test(plotting.forecast$model$residuals, type="L")
residuals.acf <- autoplot(acf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=168*5)) + scale_x_continuous() + labs(title = paste0("Series: residuals of ", plotting.forecast$method))
residuals.pacf <- autoplot(pacf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=168*5)) + scale_x_continuous() + labs(title = paste0("Series: residuals of ", plotting.forecast$method))
plot_grid(residuals.acf, residuals.pacf, nrow=2)

plot_forecast(plotting.forecast) + 
  autolayer(seis.h.test, series="Test") + 
  autolayer(seis.h.train, series="Train")
plots <- show_overlap_and_diff(
  seis.h.train, plotting.forecast$fitted, xlab=seasonality.xlab,
  base.desc = "train series",
  compare.desc = paste0("refit with ", plotting.forecast$method),
  overlap.ylab = "Mean hourly movement (nm)",
  diff.title = "Difference between ts",
  diff.ylab = "nm", diff.ylab.sec="% over ts span",
  diff.ylab.sec.accuracy = .01
)
plot_grid(plots[[1]], plots[[2]], nrow = 2)
plots <- show_overlap_and_diff(
  seis.h.test[1:length(plotting.forecast$mean)], plotting.forecast$mean, xlab=seasonality.xlab,
  base.desc = "test series",
  compare.desc = paste0("refit with ", plotting.forecast$method),
  overlap.ylab = "Mean hourly movement (nm)",
  diff.title = "Difference between ts",
  diff.ylab = "nm", diff.ylab.sec="% over ts span",
  diff.ylab.sec.accuracy = .01
)
plot_grid(plots[[1]], plots[[2]], nrow = 2)
accuracy(plotting.forecast, seis.h.test)

```




## MSTL

```{r mstl on msts}
seis.h.train.m <- msts(seis.h.train, c(24, 168))
seis.mstl <- seis.h.train.m %>% mstl(s.window="periodic", lambda=train.bc.lambda) #c(15, 7))
seis.mstl.fc <- forecast(seis.mstl, h=168*18, lambda=train.bc.lambda)

plot(InvBoxCox(seis.mstl[,2], lambda=train.bc.lambda), main="trend")
lines(trend.s, col="red")
plot(InvBoxCox(rowSums(seis.mstl[,3:4]), lambda=train.bc.lambda), main="seasonality",type="l")
lines(seasonality, col="red")
plot(InvBoxCox(seis.mstl[,5], lambda=train.bc.lambda),  main="residuals")
lines(residuals, col="red")


plotting.model <- seis.mstl
plotting.forecast <- seis.mstl.fc

autoplot(plotting.model) + xlab("Week")

gg_qqplot(plotting.model[,5]) + 
  labs(title=paste0("Q-Q plot for ", seis.mstl.fc$method, " residuals")) + ylab("Residuals quantiles")
checkresiduals(plotting.model[,5])
Box.test(plotting.forecast$model$residuals, type="L")
residuals.acf <- autoplot(acf(plotting.model[,5], na.action = na.pass, plot=F, lag.max=168*5)) + scale_x_continuous() + labs(title = paste0("Series: residuals of ", plotting.forecast$method))
residuals.pacf <- autoplot(pacf(plotting.model[,5], na.action = na.pass, plot=F, lag.max=168*5)) + scale_x_continuous() + labs(title = paste0("Series: residuals of ", plotting.forecast$method))
plot_grid(residuals.acf, residuals.pacf, nrow=2)

plot_forecast(plotting.forecast) + 
  autolayer(seis.h.test, series="Test") + 
  autolayer(seis.h.train, series="Train")
plots <- show_overlap_and_diff(
  seis.h.train, plotting.forecast$fitted, xlab=seasonality.xlab,
  base.desc = "train series",
  compare.desc = paste0("refit with ", plotting.forecast$method),
  overlap.ylab = "Mean hourly movement (nm)",
  diff.title = "Difference between ts",
  diff.ylab = "nm", diff.ylab.sec="% over ts span",
  diff.ylab.sec.accuracy = .01
)
plot_grid(plots[[1]], plots[[2]], nrow = 2)
plots <- show_overlap_and_diff(
  seis.h.test[1:length(plotting.forecast$mean)], plotting.forecast$mean, xlab=seasonality.xlab,
  base.desc = "test series",
  compare.desc = paste0("refit with ", plotting.forecast$method),
  overlap.ylab = "Mean hourly movement (nm)",
  diff.title = "Difference between ts",
  diff.ylab = "nm", diff.ylab.sec="% over ts span",
  diff.ylab.sec.accuracy = .01
)
plot_grid(plots[[1]], plots[[2]], nrow = 2)
accuracy(plotting.forecast, seis.h.test)

bptests <- data.frame(lag=integer(), `p-value`=numeric())
for (i in 1:10){
  bptests[nrow(bptests) + 1, ] <- c(i, Box.test(plotting.model[,5], lag = i, fitdf = 0, type = "Box-Pierce")$p.value)
}
bptests.plot <- 
  ggplot(bptests, aes(lag, `p.value`), pch="o") + 
    geom_point() + ylim(0,1) +
    labs(title="Box-Pierce tests for lags 1 to 10") +
    geom_hline(yintercept=0.05, linetype="dotted", color = "blue") +
    scale_x_continuous(breaks=1:10)
bptests.plot

```


```{r save RData, include=FALSE}
gc()
save.image(proj_file)
```
