```{r final-model}
# chosen.model must be c(p,d,q,P,D,Q)
# seasonality.period a number
# chosen.lambda NULL or Box-Cox lambda

seis.test.final.start <- seis.test.end + seconds(1)
seis.test.final.end <- seis.test.final.start + days(7*8) - seconds(1)
c(seis.train.start, seis.test.final.start, seis.test.final.end)

final.training <- build_ts(seis.h, periods = c(seasonality.period), start = seis.train.start, end = seis.test.end, force_ms = T)
final.testing <- build_ts(seis.h, periods = c(seasonality.period), start = seis.train.start, end = seis.test.final.end, force_ms = T)
final.testing <- window(final.testing, start = c(end(final.training)[1] + 1, 1))
if (!is.null(chosen.lambda)) {
  cat(chosen.lambda, BoxCox.lambda(final.training), chosen.lambda == BoxCox.lambda(final.training), "\n")
}

fit.name <- paste0("fit", paste0(chosen.model, collapse = ""))
forecast.name <- paste0("forecast", paste0(chosen.model, collapse = ""))
cat("SARIMA(", paste0(chosen.model[1:3], collapse = ","), ")(", paste0(chosen.model[4:6], collapse = ","), ")[", frequency(final.training), "]", sep = "")
if (!exists("final.model")) {
  cat(" fitting...")
  final.model <- Arima(final.training, chosen.model[1:3], chosen.model[4:6], lambda=chosen.lambda)
  cat("DONE")
}
if (!exists("final.forecast")) {
  cat(" forecasting...")
  final.forecast <- forecast(final.model, h=168*8, lambda=chosen.lambda)
  cat("DONE")
}
cat("\n")
plotting.model <- final.model
plotting.forecast <- final.forecast
print(plotting.model)
print(autoplot(plotting.model) + labs(subtitle = plotting.forecast$method))
checkresiduals(plotting.model)
residuals.acf <- autoplot(acf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=168*4)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method))
residuals.pacf <- autoplot(pacf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=168*4)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method))
print(plot_grid(residuals.acf, residuals.pacf, nrow=2))
print(plot_grid(
  autoplot(acf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=24)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method)),
  residuals.acf,
  autoplot(pacf(plotting.model$residuals, na.action = na.pass, plot=F, lag.max=24)) + scale_x_continuous() + labs(title = paste0("Residuals of ", plotting.forecast$method)),
  residuals.pacf,
  nrow = 2
))
print(plot_forecast(plotting.forecast) + autolayer(final.testing, series="Original") + ylab("Mean hourly movement (nm)") + xlab("Weeks") + geom_vline(aes(xintercept=as.integer(as_datetime('2020-03-14T00:00:00') - seis.train.start)/7+1), linetype=2))
plots <- show_overlap_and_diff(
  final.training, plotting.forecast$fitted, xlab=seasonality.xlab,
  base.desc = "training set",
  compare.desc = paste0("refit with ", plotting.forecast$method),
  overlap.ylab = "Mean hourly movement (nm)",
  diff.title = "Difference between ts",
  diff.ylab = "nm", diff.ylab.sec="%",
  diff.ylab.sec.accuracy = .01
)
print(plot_grid(plots[[1]], plots[[2]], nrow = 2))

cat("Test set inside the CI\n")
cat("80% CI \t ", print_dec(mean(plotting.forecast$lower[,1] < final.testing & final.testing < plotting.forecast$upper[,1], na.rm = T)*100), "%\n")
cat("95% CI \t ", print_dec(mean(plotting.forecast$lower[,2] < final.testing & final.testing < plotting.forecast$upper[,2], na.rm = T)*100), "%\n")

plots <- show_overlap_and_diff(
  final.testing, plotting.forecast$mean, xlab=seasonality.xlab,
  base.desc = "test set",
  compare.desc = paste0("forecast with ", plotting.forecast$method),
  overlap.ylab = "Mean hourly movement (nm)",
  diff.title = "Difference between ts",
  diff.ylab = "nm", diff.ylab.sec="%",
  diff.ylab.sec.accuracy = .01
)
print(plot_grid(plots[[1]] + geom_vline(aes(xintercept=as.integer(as_datetime('2020-03-14T00:00:00') - seis.train.start)/7+1), linetype=2),
                plots[[2]] + geom_vline(aes(xintercept=as.integer(as_datetime('2020-03-14T00:00:00') - seis.train.start)/7+1), linetype=2),
                nrow = 2
                ))

print(accuracy(plotting.forecast, final.testing))
# qqPlot(plotting.model$residuals, main = paste0("Q-Q plot for ", plotting.forecast$method), xlab = "residuals")
print(gg_qqplot(plotting.model$residuals) + 
    labs(title=paste0("Q-Q plot for ", plotting.forecast$method, " residuals")) + ylab("Residuals quantiles")
)

```


```{r seasonalities/seasonplot}
before.lockdown.start <- seis.train.start
before.lockdown.end <- as_datetime('2020-03-14T00:00:00') - seconds(1)
after.lockdown.start <- as_datetime('2020-03-14T00:00:00')
after.lockdown.end <- as_datetime('2020-04-26T00:00:00') - seconds(1)
before.lockdown <- build_ts(seis.h, periods = c(24), start = before.lockdown.start, end = before.lockdown.end, force_ms = T)
after.lockdown <- build_ts(seis.h, periods = c(24), start = after.lockdown.start, end = after.lockdown.end, force_ms = T)
# We first check the seasonplots, highlighting different weekdays. We divide by sd to account for spikes
seasonplot(before.lockdown/sd(before.lockdown, na.rm=T), type="l", col=rainbow(7), main="Seasonal plot: before lockdown")
legend("topleft", legend=weekdays(before.lockdown.start + (as.difftime(c(0:6), units="days"))), col=rainbow(7), lty=1, cex=0.8)
seasonplot(after.lockdown/sd(after.lockdown, na.rm=T), type="l", col=rainbow(7)[c(6:7,1:5)], main="Seasonal plot: after lockdown")
legend("topleft", legend=weekdays(after.lockdown.start + (as.difftime(c(0:6), units="days")))[c(3:7,1:2)], col=rainbow(7), lty=1, cex=0.8)

weekdays <- c("Monday", "Tuesday", "Wednseday", "Thursday", "Friday", "Saturday", "Sunday")
```


```{r seasonalities/before}
aggregated.before.lockdown <- seasonality.aggregate(before.lockdown)
season.before.lockdown.24 <- trend_season(aggregated.before.lockdown, 24)
season.before.lockdown.168 <- trend_season(aggregated.before.lockdown-season.before.lockdown.24$seasonal, 168)
season.before.lockdown.24 <- trend_season(aggregated.before.lockdown-season.before.lockdown.168$seasonal, 24)
season.before.lockdown.168 <- trend_season(aggregated.before.lockdown-season.before.lockdown.24$seasonal, 168)
# this third iteration isn't actually needed
season.before.lockdown.24 <- trend_season(aggregated.before.lockdown-season.before.lockdown.168$seasonal, 24)
season.before.lockdown.168 <- trend_season(aggregated.before.lockdown-season.before.lockdown.24$seasonal, 168)
season.before.lockdown.168.df <- data.frame(Hour=rep(1:24, 7), figure=season.before.lockdown.168$figure[1:168], sd=season.before.lockdown.168$sd[1:168], Weekday=rep(weekdays, each=24))
seasonbase.before.lockdown.24 <- trend_season(aggregated.before.lockdown, 24)
seasonbase.before.lockdown.24.df <- data.frame(Hour=1:24, figure=seasonbase.before.lockdown.24$figure, sd=seasonbase.before.lockdown.24$sd)
seasonbase.before.lockdown.168 <- trend_season(aggregated.before.lockdown, 168)
seasonbase.before.lockdown.168.df <- data.frame(Hour=rep(1:24, 7), figure=seasonbase.before.lockdown.168$figure[1:168], sd=seasonbase.before.lockdown.168$sd[1:168], Weekday=rep(weekdays, each=24))


plot_grid(
  autoplot(ts(seasonbase.before.lockdown.24.df$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() + geom_line(aes(col="Direct daily"), size=1.5) +
    geom_line(aes(y=season.before.lockdown.24.df$figure, col="Multi daily")) +
    scale_colour_manual("", values=c("purple", "yellow"), breaks=c("Direct daily", "Multi daily")),
  autoplot(ts(seasonbase.before.lockdown.168.df$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() + geom_line(aes(col="Direct weekly"), size=1.5) +
    geom_line(aes(y=season.before.lockdown.168.df$figure + rep(season.before.lockdown.24.df$figure, 7), col="Multi w+d")) +
    #geom_line(aes(y=rep(seasonbase.before.lockdown.24$figure, 7), col="Direct daily"), size=1.5) +
    #geom_line(aes(y=rep(season.before.lockdown.24$figure, 7), col="Multi daily")) +
    geom_line(aes(y=season.before.lockdown.168.df$figure, col="Multi weekly")) +
    scale_colour_manual("", values=c("red", "purple", "blue", "yellow", "green"), breaks=c("Direct weekly", "Direct daily", "Multi" %s+% c(" weekly", " daily", " w+d"))),
  nrow = 2)


```

```{r seasonalities/lockdown}
aggregated.after.lockdown <- seasonality.aggregate(after.lockdown)
season.after.lockdown.24 <- trend_season(aggregated.after.lockdown, 24)
season.after.lockdown.168 <- trend_season(aggregated.after.lockdown-season.after.lockdown.24$seasonal, 168)
season.after.lockdown.24 <- trend_season(aggregated.after.lockdown-season.after.lockdown.168$seasonal, 24)
season.after.lockdown.168 <- trend_season(aggregated.after.lockdown-season.after.lockdown.24$seasonal, 168)
season.after.lockdown.24 <- trend_season(aggregated.after.lockdown-season.after.lockdown.168$seasonal, 24)
season.after.lockdown.168 <- trend_season(aggregated.after.lockdown-season.after.lockdown.24$seasonal, 168)
season.after.lockdown.168.df <- data.frame(Hour=rep(1:24, 7), figure=season.after.lockdown.168$figure[c(49:168,1:48)], sd=season.after.lockdown.168$sd[c(49:168,1:48)], Weekday=rep(weekdays, each=24))
seasonbase.after.lockdown.24 <- trend_season(aggregated.after.lockdown, 24)
seasonbase.after.lockdown.24 <- trend_season(aggregated.after.lockdown, 24)
seasonbase.after.lockdown.24.df <- data.frame(Hour=1:24, figure=seasonbase.after.lockdown.24$figure, sd=seasonbase.after.lockdown.24$sd)
seasonbase.after.lockdown.168 <- trend_season(aggregated.after.lockdown, 168)
seasonbase.after.lockdown.168.df <- data.frame(Hour=rep(1:24, 7), figure=seasonbase.after.lockdown.168$figure[c(49:168,1:48)], sd=seasonbase.after.lockdown.168$sd[c(49:168,1:48)], Weekday=rep(weekdays, each=24))

plot_grid(
  autoplot(ts(seasonbase.after.lockdown.24.df$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() + geom_line(aes(col="Direct daily"), size=1.5) +
    geom_line(aes(y=season.after.lockdown.24$figure, col="Multi daily")) +
    scale_colour_manual("", values=c("purple", "yellow"), breaks=c("Direct daily", "Multi daily")),
  autoplot(ts(seasonbase.after.lockdown.168.df$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() + geom_line(aes(col="Direct weekly"), size=1.5) +
    geom_line(aes(y=season.after.lockdown.168.df$figure + rep(season.after.lockdown.24$figure, 7), col="Multi w+d")) +
    #geom_line(aes(y=rep(seasonbase.after.lockdown.24$figure, 7), col="Direct daily"), size=1.5) +
    #geom_line(aes(y=rep(season.after.lockdown.24$figure, 7), col="Multi daily")) +
    geom_line(aes(y=season.after.lockdown.168.df$figure, col="Multi weekly")) +
    scale_colour_manual("", values=c("red", "purple", "blue", "yellow", "green"), breaks=c("Direct weekly", "Direct daily", "Multi" %s+% c(" weekly", " daily", " w+d"))),
  nrow = 2)

```

```{r seasonalities/before-after-compare}

plot_grid(
  autoplot(ts(season.after.lockdown.24$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() +
    geom_ribbon(aes(ymin = season.after.lockdown.24$figure  - season.after.lockdown.24$sd,  ymax = season.after.lockdown.24$figure  + season.after.lockdown.24$sd),  alpha=0.5, fill = "mediumpurple1") +
    geom_line(aes(col="After lockdown")) +
    geom_ribbon(aes(ymin = season.before.lockdown.24$figure - season.before.lockdown.24$sd, ymax = season.before.lockdown.24$figure + season.before.lockdown.24$sd), alpha=0.5, fill = "lightcoral") +
    geom_line(aes(y=season.before.lockdown.24$figure, col="Before lockdown")) +
    scale_colour_manual("", values=c("purple", "red"), breaks=c("After lockdown", "Before lockdown")),
  autoplot(ts(season.after.lockdown.168.df$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() +
    geom_ribbon(aes(ymin = season.after.lockdown.168.df$figure  - season.after.lockdown.168.df$sd,  ymax = season.after.lockdown.168.df$figure  + season.after.lockdown.168.df$sd),  alpha=0.5, fill = "mediumpurple1") +
    geom_line(aes(col="After lockdown")) +
    geom_ribbon(aes(ymin = season.before.lockdown.168.df$figure - season.before.lockdown.168.df$sd, ymax = season.before.lockdown.168.df$figure + season.before.lockdown.168.df$sd), alpha=0.5, fill = "lightcoral") +
    geom_line(aes(y=season.before.lockdown.168.df$figure, col="Before lockdown")) +
    scale_colour_manual("", values=c("purple", "red"), breaks=c("After lockdown", "Before lockdown")),
  nrow = 2)


autoplot(ts(seasonbase.after.lockdown.168.df$figure, frequency=1)) + ylab("") + xlab("Hours") + scale_x_continuous() +
  geom_ribbon(aes(ymin = (seasonbase.after.lockdown.168.df$figure - seasonbase.after.lockdown.168.df$sd), ymax = (seasonbase.after.lockdown.168.df$figure + seasonbase.after.lockdown.168.df$sd)), fill = "mediumpurple1", alpha=0.5) +
  geom_line(aes(col="After lockdown")) +
  geom_ribbon(aes(ymin = seasonbase.before.lockdown.168.df$figure - seasonbase.before.lockdown.168.df$sd, ymax = seasonbase.before.lockdown.168.df$figure + seasonbase.before.lockdown.168.df$sd), fill = "lightcoral", alpha=0.5) +
  geom_line(aes(y=seasonbase.before.lockdown.168.df$figure, col="Before lockdown")) +
  scale_colour_manual("", values=c("purple", "red"), breaks=c("After lockdown", "Before lockdown"))
```
```{r seasonalities/seasonplot-mean-sd}
ggplot(data=seasonbase.before.lockdown.168.df) +
  geom_line(aes(Hour, figure - sd, col=Weekday), alpha=.1) +
  geom_line(aes(Hour, figure + sd, col=Weekday), alpha=.1) +
  geom_ribbon(aes(Hour, ymin = figure - sd, ymax = figure + sd, fill = Weekday), alpha=0.1, show.legend=F) +
  geom_line(aes(Hour, figure, col=Weekday)) +
  ylab("Mean hourly movement (nm)") +
  labs(title="Seasonal plot: before lockdown") +
  scale_color_manual(values = rainbow(7), breaks=weekdays, aesthetics = c("colour", "fill"))


ggplot(data=seasonbase.after.lockdown.168.df) +
  geom_line(aes(Hour, figure - sd, col=Weekday), alpha=.1) +
  geom_line(aes(Hour, figure + sd, col=Weekday), alpha=.1) +
  geom_ribbon(aes(Hour, ymin = figure - sd, ymax = figure + sd, fill = Weekday), alpha=0.1, show.legend=F) +
  geom_line(aes(Hour, figure, col=Weekday)) +
  ylab("Mean hourly movement (nm)") +
  labs(title="Seasonal plot: after lockdown") +
  scale_color_manual(values = rainbow(7), breaks=weekdays, aesthetics = c("colour", "fill"))
```